Update index.js
change   require('./dot-env') ()  to  require('./dot-env')  

to resolve below error:

 TypeError: require(...) is not a function
dev-api-1  |     at Object.<anonymous> (/app/node_modules/@quisitive/node-application/index.js:5:21)